### ISSUE TITLE
Timestamps uninitialized

### ISSUE THREAD

**Issue by ktscholl** [lair-framework/go-nmap#4]
During unmarshalling of XML, Timestamp fields were set to 0 and time data was not being stored. It looks like the UnmarshalXMLAttr function should use a *Timestamp instead of a Timestamp. [Here](https://github.com/lair-framework/go-nmap/pull/3)'s a  a pull request that fixes this.
https://github.com/lair-framework/go-nmap/pull/3

**Comment by jamesbcook** [comment]
PR merged
